{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodingError"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"In the event we recieved data but it did not conform to the Race Data Model, return this error.","type":"text"}],"kind":"symbol","sections":[],"metadata":{"title":"RaceDateServiceError.decodingError(_:)","roleHeading":"Case","symbolKind":"case","externalID":"s:14EntainNextToGo20RaceDateServiceErrorO08decodingH0yACs0H0_pcACmF","modules":[{"name":"EntainNextToGo"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"decodingError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo\/RaceDateServiceError\/decodingError(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/entainnexttogo\/racedateserviceerror\/decodingerror(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo","doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo\/RaceDateServiceError"]]},"references":{"doc://com.seansmith.EntainNextToGo/documentation/EntainNextToGo/RaceDateServiceError/decodingError(_:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodingError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"url":"\/documentation\/entainnexttogo\/racedateserviceerror\/decodingerror(_:)","title":"RaceDateServiceError.decodingError(_:)","identifier":"doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo\/RaceDateServiceError\/decodingError(_:)","abstract":[{"text":"In the event we recieved data but it did not conform to the Race Data Model, return this error.","type":"text"}]},"doc://com.seansmith.EntainNextToGo/documentation/EntainNextToGo":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo","url":"\/documentation\/entainnexttogo","type":"topic","title":"EntainNextToGo","role":"collection"},"doc://com.seansmith.EntainNextToGo/documentation/EntainNextToGo/RaceDateServiceError":{"abstract":[{"type":"text","text":"Handle scenario for invalid URL."}],"role":"symbol","type":"topic","url":"\/documentation\/entainnexttogo\/racedateserviceerror","identifier":"doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo\/RaceDateServiceError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RaceDateServiceError","kind":"identifier"}],"title":"RaceDateServiceError","kind":"symbol","navigatorTitle":[{"text":"RaceDateServiceError","kind":"identifier"}]}}}