{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo","doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo\/RaceDateServiceError"]]},"metadata":{"symbolKind":"case","title":"RaceDateServiceError.networkError(_:)","externalID":"s:14EntainNextToGo20RaceDateServiceErrorO07networkH0yAC10Foundation8URLErrorVcACmF","role":"symbol","modules":[{"name":"EntainNextToGo"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkError"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation8URLErrorV","kind":"typeIdentifier","text":"URLError"},{"text":")","kind":"text"}]},"abstract":[{"text":"In the event that the network request fails, return the network error.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/entainnexttogo\/racedateserviceerror\/networkerror(_:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo\/RaceDateServiceError\/networkError(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URLError","preciseIdentifier":"s:10Foundation8URLErrorV","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"references":{"doc://com.seansmith.EntainNextToGo/documentation/EntainNextToGo":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo","url":"\/documentation\/entainnexttogo","type":"topic","title":"EntainNextToGo","role":"collection"},"doc://com.seansmith.EntainNextToGo/documentation/EntainNextToGo/RaceDateServiceError":{"abstract":[{"type":"text","text":"Handle scenario for invalid URL."}],"role":"symbol","type":"topic","url":"\/documentation\/entainnexttogo\/racedateserviceerror","identifier":"doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo\/RaceDateServiceError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RaceDateServiceError","kind":"identifier"}],"title":"RaceDateServiceError","kind":"symbol","navigatorTitle":[{"text":"RaceDateServiceError","kind":"identifier"}]},"doc://com.seansmith.EntainNextToGo/documentation/EntainNextToGo/RaceDateServiceError/networkError(_:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLError","preciseIdentifier":"s:10Foundation8URLErrorV"},{"text":")","kind":"text"}],"url":"\/documentation\/entainnexttogo\/racedateserviceerror\/networkerror(_:)","title":"RaceDateServiceError.networkError(_:)","identifier":"doc:\/\/com.seansmith.EntainNextToGo\/documentation\/EntainNextToGo\/RaceDateServiceError\/networkError(_:)","abstract":[{"text":"In the event that the network request fails, return the network error.","type":"text"}]}}}